services:
  # SnapDog2 application - container-only development with full debugging
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development # Multi-stage development target
    volumes:
      - .:/app:cached # Mount source code for hot reload
      - snapcast_sinks:/snapsinks # Shared audio sinks with snapcast-server
      - ~/.nuget/local:/app/.nuget/local:ro # Direct bind mount for local NuGet packages
    env_file:
      - ./devcontainer/.env
    environment:
      - DOTNET_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
    depends_on:
      - redis
      - snapcast-server
      - mqtt
      - navidrome
      - otel-collector
    networks:
      snapdog-dev:
    #        ipv4_address: 172.25.0.2
    # Enable debugger
    ports:
      - "5555:5555"
    stdin_open: true
    tty: true

  # Frontend development server with hot reload
  frontend:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - ./SnapDog2.WebUI:/app:cached
      - frontend_node_modules:/app/node_modules # Named volume for node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    networks:
      snapdog-dev:
    ports:
      - "5173:5173"
    depends_on:
      - app
    stdin_open: true
    tty: true
  # Redis for persistent state storage
  redis:
    image: redis:8-alpine
    command: redis-server --appendonly yes --appendfsync everysec
    volumes:
      - redis_data:/data
    networks:
      snapdog-dev:
    #        ipv4_address: 172.25.0.15
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Caddy reverse proxy with dashboard - SINGLE PORT TO HOST
  caddy:
    image: caddy:2-alpine
    ports:
      - "8000:80" # Only exposed port!
    volumes:
      - ./devcontainer/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./devcontainer/caddy/site:/srv:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
      - snapcast-server
      - snapcast-client-living-room
      - snapcast-client-kitchen
      - snapcast-client-bedroom
      - navidrome
      - grafana
    networks:
      snapdog-dev:
    #        ipv4_address: 172.25.0.4
    restart: unless-stopped

  # Snapcast Server - NO HOST PORTS
  snapcast-server:
    build:
      context: ./devcontainer/snapcast-server
    hostname: snapcast-server
    env_file:
      - ./devcontainer/.env
    ports:
      - "1705:1705" # Snapcast server port
    volumes:
      - snapcast_sinks:/snapsinks # Shared audio sinks with app container
    networks:
      snapdog-dev:
    #        ipv4_address: 172.25.0.5
    restart: unless-stopped

  # Living room client
  snapcast-client-living-room:
    build:
      context: ./devcontainer/snapcast-client
    restart: unless-stopped
    depends_on:
      - snapcast-server
    environment:
      - SNAPSERVER_HOST=snapcast-server # IP address of snapcast-server
      - CLIENT_ID=living-room
      - CLIENT_NAME=Living Room
      - FIXED_MAC_ADDRESS=02:42:ac:11:00:10
    networks:
      snapdog-dev:
        #        ipv4_address: 172.25.0.6
        mac_address: 02:42:ac:11:00:10

  # Kitchen client
  snapcast-client-kitchen:
    build:
      context: ./devcontainer/snapcast-client
    restart: unless-stopped
    depends_on:
      - snapcast-server
    environment:
      - SNAPSERVER_HOST=snapcast-server
      - CLIENT_ID=kitchen
      - CLIENT_NAME=Kitchen
      - FIXED_MAC_ADDRESS=02:42:ac:11:00:11
    networks:
      snapdog-dev:
        #        ipv4_address: 172.25.0.7
        mac_address: 02:42:ac:11:00:11

  # Bedroom client
  snapcast-client-bedroom:
    build:
      context: ./devcontainer/snapcast-client
    restart: unless-stopped
    depends_on:
      - snapcast-server
    environment:
      - SNAPSERVER_HOST=snapcast-server
      - CLIENT_ID=bedroom
      - CLIENT_NAME=Bedroom
      - FIXED_MAC_ADDRESS=02:42:ac:11:00:12
    networks:
      snapdog-dev:
        #        ipv4_address: 172.25.0.8
        mac_address: 02:42:ac:11:00:12

  # MQTT Broker
  mqtt:
    image: eclipse-mosquitto:2.0
    volumes:
      - ./devcontainer/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./devcontainer/mosquitto/passwd:/mosquitto/config/passwd
    #      - mqtt_data:/mosquitto/data
    #      - mqtt_logs:/mosquitto/log
    ports:
      - "1883:1883" # MQTT port
    environment:
      - MOSQUITTO_LOG_LEVEL=debug
    command: ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf", "-v"]
    networks:
      snapdog-dev:
    #        ipv4_address: 172.25.0.3
    restart: unless-stopped

  # Navidrome - NO HOST PORTS (via Caddy)
  navidrome:
    image: deluan/navidrome:latest
    environment:
      ND_ENABLEINSIGHTSCOLLECTOR: "false" # Disable insights collector
      ND_SCANSCHEDULE: "1h"
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: "24h"
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_BASEURL: "/music" # Configure for reverse proxy
    volumes:
      - ./devcontainer/music:/music:ro
      - navidrome_data:/data
    networks:
      snapdog-dev:
    #        ipv4_address: 172.25.0.9
    restart: unless-stopped

  # KNX Gateway Simulator - Custom Alpine-based container
  knxd:
    build:
      context: ./devcontainer/knxd
      dockerfile: Dockerfile
    environment:
      - ADDRESS=0.0.1 # KNX daemon address (standard format)
      - CLIENT_ADDRESS=0.0.2:8 # Client address range (start:count)
      - INTERFACE=dummy # Use dummy interface for simulation
      - DEBUG_LEVEL=verbose # Debug level (verbose for troubleshooting)
      - FILTERS=single,pace:queue # Filters with queue to avoid warnings
    ports:
      - "3671:3671" # KNX/IP port
    networks:
      snapdog-dev:
    #        ipv4_address: 172.25.0.10
    restart: unless-stopped
    # Security: Run as non-root with minimal capabilities
    user: "1000:1000"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    # Health check
    healthcheck:
      test: ["CMD", "netstat", "-ln"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # ═══════════════════════════════════════════════════════════════════════════════
  # Observability Stack - OTEL Collector + Grafana (Simple & Reliable)
  # ═══════════════════════════════════════════════════════════════════════════════

  # OpenTelemetry Collector (Standalone for development)
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.112.0
    container_name: snapdog-otel-collector
    hostname: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./devcontainer/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    #    ports:
    #      - "4317:4317" # OTLP gRPC receiver
    #      - "4318:4318" # OTLP HTTP receiver
    #      - "8889:8889" # Prometheus metrics endpoint
    #      - "8888:8888" # OTEL collector own metrics
    networks:
      snapdog-dev:
    #        ipv4_address: 172.25.0.20
    restart: unless-stopped

  # Grafana for observability dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: snapdog-grafana
    hostname: grafana
    ports:
      - "3301:3000" # Grafana UI
    volumes:
      - grafana-data:/var/lib/grafana
      - ./devcontainer/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_ROOT_URL=http://localhost:8000/grafana/
    depends_on:
      - otel-collector
    networks:
      snapdog-dev:
    #        ipv4_address: 172.25.0.21
    restart: unless-stopped

  # KNX Monitor - Visual debugging tool for KNX bus activity with web interface
  knx-monitor:
    image: ghcr.io/metaneutrons/knxmonitor:latest
    volumes:
      - ./devcontainer/knx-groupaddresses.csv:/app/knx-groupaddresses.csv:ro # KNX group addresses database
    environment:
      - TZ=Europe/Berlin # Set timezone for proper log timestamps
    command: [
        "-g",
        "knxd",
        "--csv",
        "/app/knx-groupaddresses.csv",
        "--logging-mode", # Force web interface mode
      ]
    depends_on:
      knxd:
        condition: service_healthy
    networks:
      snapdog-dev:
    #        ipv4_address: 172.25.0.14
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8671/ready"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      - "traefik.enable=false" # Exposed via Caddy instead
      - "com.docker.compose.service=knx-monitor"

volumes:
  snapcast_sinks: # Shared volume for audio sinks between snapcast-server and app
  redis_data:
  mqtt_data:
  mqtt_logs:
  navidrome_data:
  caddy_data:
  caddy_config:
  grafana-data:
  frontend_node_modules: # Node.js dependencies for frontend development

networks:
  snapdog-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
