namespace SnapDog2.Tests.Blueprint;

/// <summary>
/// Complete SnapDog2 system specification as fluent blueprint.
/// Single source of truth for all commands, status, protocols, and implementation requirements.
/// </summary>
public static class SnapDogBlueprint
{
    public static readonly Blueprint Spec = Blueprint
        .Define()
        // === ZONE PLAYBACK COMMANDS ===
        .Command("PLAY")
        .Zone()
        .Mqtt()
        .Knx()
        .Post("/api/v1/zones/{zoneIndex:int}/play")
        .Description("Start playback in a zone")
        .Command("PAUSE")
        .Zone()
        .Mqtt()
        .Knx()
        .Post("/api/v1/zones/{zoneIndex:int}/pause")
        .Description("Pause playback in a zone")
        .Command("STOP")
        .Zone()
        .Mqtt()
        .Knx()
        .Post("/api/v1/zones/{zoneIndex:int}/stop")
        .Description("Stop playback in a zone")
        // === VOLUME COMMANDS ===
        .Command("VOLUME")
        .Zone()
        .Mqtt()
        .Put("/api/v1/zones/{zoneIndex:int}/volume")
        .Description("Set zone volume to specific level")
        .Exclude(Protocol.Knx, "Handled by dedicated KNX volume actuators")
        .Command("VOLUME_UP")
        .Zone()
        .Mqtt()
        .Post("/api/v1/zones/{zoneIndex:int}/volume/up")
        .Description("Increase zone volume")
        .Exclude(Protocol.Knx, "Handled by dedicated KNX volume actuators")
        .Command("VOLUME_DOWN")
        .Zone()
        .Mqtt()
        .Post("/api/v1/zones/{zoneIndex:int}/volume/down")
        .Description("Decrease zone volume")
        .Exclude(Protocol.Knx, "Handled by dedicated KNX volume actuators")
        // === MUTE COMMANDS ===
        .Command("MUTE")
        .Zone()
        .Mqtt()
        .Put("/api/v1/zones/{zoneIndex:int}/mute")
        .Description("Set zone mute state")
        .Exclude(Protocol.Knx, "Handled by dedicated KNX mute actuators")
        .Command("MUTE_TOGGLE")
        .Zone()
        .Mqtt()
        .Post("/api/v1/zones/{zoneIndex:int}/mute/toggle")
        .Description("Toggle zone mute state")
        .Exclude(Protocol.Knx, "Toggle commands require state synchronization")
        // === TRACK COMMANDS ===
        .Command("TRACK")
        .Zone()
        .Mqtt()
        .Put("/api/v1/zones/{zoneIndex:int}/track")
        .Description("Set current track by index")
        .Exclude(Protocol.Knx, "Complex track navigation not suitable for building automation")
        .Command("TRACK_NEXT")
        .Zone()
        .Mqtt()
        .Post("/api/v1/zones/{zoneIndex:int}/next")
        .Description("Skip to next track")
        .Exclude(Protocol.Knx, "Complex track navigation not suitable for building automation")
        .Command("TRACK_PREVIOUS")
        .Zone()
        .Mqtt()
        .Post("/api/v1/zones/{zoneIndex:int}/previous")
        .Description("Skip to previous track")
        .Exclude(Protocol.Knx, "Complex track navigation not suitable for building automation")
        .Command("TRACK_PLAY_INDEX")
        .Zone()
        .Mqtt()
        .Knx()
        .Post("/api/v1/zones/{zoneIndex:int}/play/{trackIndex:int}")
        .Description("Play specific track by index")
        .Command("TRACK_PLAY_URL")
        .Zone()
        .Mqtt()
        .Post("/api/v1/zones/{zoneIndex:int}/play/url")
        .Description("Play direct URL stream")
        .Exclude(Protocol.Knx, "KNX cannot transmit URL strings effectively")
        .Command("TRACK_POSITION")
        .Zone()
        .Mqtt()
        .Put("/api/v1/zones/{zoneIndex:int}/track/position")
        .Description("Seek to position in track")
        .Exclude(Protocol.Knx, "KNX lacks precision for millisecond-based seeking")
        .Command("TRACK_PROGRESS")
        .Zone()
        .Mqtt()
        .Put("/api/v1/zones/{zoneIndex:int}/track/progress")
        .Description("Seek to progress percentage")
        .Exclude(Protocol.Knx, "KNX lacks precision for percentage-based seeking")
        .Command("TRACK_REPEAT")
        .Zone()
        .Mqtt()
        .Knx()
        .Put("/api/v1/zones/{zoneIndex:int}/repeat/track")
        .Description("Set track repeat mode")
        .Command("TRACK_REPEAT_TOGGLE")
        .Zone()
        .Mqtt()
        .Knx()
        .Post("/api/v1/zones/{zoneIndex:int}/repeat/track/toggle")
        .Description("Toggle track repeat mode")
        // === PLAYLIST COMMANDS ===
        .Command("PLAYLIST")
        .Zone()
        .Mqtt()
        .Put("/api/v1/zones/{zoneIndex:int}/playlist")
        .Description("Set current playlist")
        .Command("PLAYLIST_NEXT")
        .Zone()
        .Mqtt()
        .Post("/api/v1/zones/{zoneIndex:int}/next/playlist")
        .Description("Switch to next playlist")
        .Exclude(Protocol.Knx, "Complex playlist navigation not suitable for building automation")
        .Command("PLAYLIST_PREVIOUS")
        .Zone()
        .Mqtt()
        .Post("/api/v1/zones/{zoneIndex:int}/previous/playlist")
        .Description("Switch to previous playlist")
        .Exclude(Protocol.Knx, "Complex playlist navigation not suitable for building automation")
        .Command("PLAYLIST_SHUFFLE")
        .Zone()
        .Mqtt()
        .Put("/api/v1/zones/{zoneIndex:int}/shuffle")
        .Description("Set playlist shuffle mode")
        .Exclude(Protocol.Knx, "Complex state management not suitable for KNX")
        .Command("PLAYLIST_SHUFFLE_TOGGLE")
        .Zone()
        .Mqtt()
        .Post("/api/v1/zones/{zoneIndex:int}/shuffle/toggle")
        .Description("Toggle playlist shuffle mode")
        .Exclude(Protocol.Knx, "Toggle commands require state synchronization")
        .Command("PLAYLIST_REPEAT")
        .Zone()
        .Mqtt()
        .Knx()
        .Put("/api/v1/zones/{zoneIndex:int}/repeat")
        .Description("Set playlist repeat mode")
        .Command("PLAYLIST_REPEAT_TOGGLE")
        .Zone()
        .Mqtt()
        .Knx()
        .Post("/api/v1/zones/{zoneIndex:int}/repeat/toggle")
        .Description("Toggle playlist repeat mode")
        // === CLIENT COMMANDS ===
        .Command("CLIENT_VOLUME")
        .Client()
        .Mqtt()
        .Put("/api/v1/clients/{clientIndex:int}/volume")
        .Description("Set client volume level")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        .Command("CLIENT_VOLUME_UP")
        .Client()
        .Mqtt()
        .Post("/api/v1/clients/{clientIndex:int}/volume/up")
        .Description("Increase client volume")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        .Command("CLIENT_VOLUME_DOWN")
        .Client()
        .Mqtt()
        .Post("/api/v1/clients/{clientIndex:int}/volume/down")
        .Description("Decrease client volume")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        .Command("CLIENT_MUTE")
        .Client()
        .Mqtt()
        .Put("/api/v1/clients/{clientIndex:int}/mute")
        .Description("Set client mute state")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        .Command("CLIENT_MUTE_TOGGLE")
        .Client()
        .Mqtt()
        .Post("/api/v1/clients/{clientIndex:int}/mute/toggle")
        .Description("Toggle client mute state")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        .Command("CLIENT_LATENCY")
        .Client()
        .Mqtt()
        .Put("/api/v1/clients/{clientIndex:int}/latency")
        .Description("Set client audio latency")
        .Exclude(Protocol.Knx, "Network-specific setting not suitable for building automation")
        .Command("CLIENT_NAME")
        .Client()
        .Mqtt()
        .Put("/api/v1/clients/{clientIndex:int}/name")
        .Description("Set client name")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        .Command("CLIENT_ZONE")
        .Client()
        .Mqtt()
        .Put("/api/v1/clients/{clientIndex:int}/zone")
        .Description("Assign client to zone")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        // === CONTROL COMMANDS ===
        .Command("CONTROL")
        .Zone()
        .Mqtt()
        .Post("/api/v1/zones/{zoneIndex:int}/control")
        .Description("General zone control command")
        .Command("ZONE_NAME")
        .Zone()
        .Description("Set zone name")
        .Exclude(Protocol.Knx, "KNX cannot transmit string names effectively")
        .Exclude(Protocol.Mqtt, "MQTT should not change zone name")
        .Exclude(Protocol.Api, "API should not change zone name")
        // === SYSTEM STATUS ===
        .Status("SYSTEM_STATUS")
        .Global()
        .Mqtt()
        .Get("/api/v1/system/status")
        .Description("Overall system health and status")
        .Exclude(Protocol.Knx, "Read-only system information not actionable via KNX")
        .Status("VERSION_INFO")
        .Global()
        .Mqtt()
        .Get("/api/v1/system/version")
        .Description("System version information")
        .Status("SERVER_STATS")
        .Global()
        .Mqtt()
        .Get("/api/v1/system/stats")
        .Description("Server performance statistics")
        .Status("ZONES_INFO")
        .Global()
        .Mqtt()
        .Get("/api/v1/zones")
        .Description("Information about all zones")
        .Exclude(Protocol.Knx, "Read-only system information not actionable via KNX")
        .Status("CLIENTS_INFO")
        .Global()
        .Mqtt()
        .Get("/api/v1/clients")
        .Description("Information about all clients")
        .Exclude(Protocol.Knx, "Read-only system information not actionable via KNX")
        // === ZONE STATUS ===
        .Status("ZONE_STATE")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}")
        .Description("Complete zone state information")
        .Status("ZONE_NAME_STATUS")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/name")
        .Description("Zone name")
        .Exclude(Protocol.Knx, "Read-only string information not actionable via KNX")
        .Status("VOLUME_STATUS")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/volume")
        .Description("Current zone volume level")
        .Status("MUTE_STATUS")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/mute")
        .Description("Current zone mute state")
        .Status("PLAYBACK_STATE")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/playback")
        .Description("Current playback state")
        // === TRACK STATUS ===
        .Status("TRACK_STATUS")
        .Zone()
        .Mqtt()
        .Knx()
        .Get("/api/v1/zones/{zoneIndex:int}/track")
        .Description("Current track information")
        .Status("TRACK_METADATA")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/track/metadata")
        .Description("Track metadata (title, artist, album, etc.)")
        .Exclude(Protocol.Knx, "Read-only metadata not actionable via KNX")
        .Status("TRACK_METADATA_DURATION")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/track/duration")
        .Description("Track duration in milliseconds")
        .Exclude(Protocol.Knx, "Read-only metadata not actionable via KNX")
        .Status("TRACK_METADATA_TITLE")
        .Zone()
        .Mqtt()
        .Knx()
        .Get("/api/v1/zones/{zoneIndex:int}/track/title")
        .Description("Track title")
        .Status("TRACK_METADATA_ARTIST")
        .Zone()
        .Mqtt()
        .Knx()
        .Get("/api/v1/zones/{zoneIndex:int}/track/artist")
        .Description("Track artist")
        .Status("TRACK_METADATA_ALBUM")
        .Zone()
        .Mqtt()
        .Knx()
        .Get("/api/v1/zones/{zoneIndex:int}/track/album")
        .Description("Track album")
        .Status("TRACK_METADATA_COVER")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/track/cover")
        .Description("Track cover art URL")
        .Exclude(Protocol.Knx, "KNX cannot transmit URL strings effectively")
        .Status("TRACK_PLAYING_STATUS")
        .Zone()
        .Mqtt()
        .Knx()
        .Get("/api/v1/zones/{zoneIndex:int}/track/playing")
        .Description("Current playing state")
        .Status("TRACK_POSITION_STATUS")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/track/position")
        .Description("Current track position")
        .Status("TRACK_PROGRESS_STATUS")
        .Zone()
        .Mqtt()
        .Knx()
        .Get("/api/v1/zones/{zoneIndex:int}/track/progress")
        .Description("Track progress percentage")
        .Status("TRACK_REPEAT_STATUS")
        .Zone()
        .Mqtt()
        .Knx()
        .Get("/api/v1/zones/{zoneIndex:int}/repeat/track")
        .Description("Track repeat mode status")
        // === PLAYLIST STATUS ===
        .Status("PLAYLIST_STATUS")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/playlist")
        .Description("Current playlist information")
        .Status("PLAYLIST_INFO")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/playlist/info")
        .Description("Detailed playlist information")
        .Status("PLAYLIST_NAME_STATUS")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/playlist/name")
        .Description("Current playlist name")
        .RecentlyAdded()
        .Status("PLAYLIST_COUNT_STATUS")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/playlist/count")
        .Description("Number of tracks in current playlist")
        .RecentlyAdded()
        .Status("PLAYLIST_SHUFFLE_STATUS")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/shuffle")
        .Description("Playlist shuffle mode status")
        .Status("PLAYLIST_REPEAT_STATUS")
        .Zone()
        .Mqtt()
        .Get("/api/v1/zones/{zoneIndex:int}/repeat")
        .Description("Playlist repeat mode status")
        // === CLIENT STATUS ===
        .Status("CLIENT_STATE")
        .Client()
        .Mqtt()
        .Get("/api/v1/clients/{clientIndex:int}")
        .Description("Complete client state information")
        .Status("CLIENT_VOLUME_STATUS")
        .Client()
        .Mqtt()
        .Get("/api/v1/clients/{clientIndex:int}/volume")
        .Description("Current client volume level")
        .Status("CLIENT_MUTE_STATUS")
        .Client()
        .Mqtt()
        .Get("/api/v1/clients/{clientIndex:int}/mute")
        .Description("Current client mute state")
        .Status("CLIENT_LATENCY_STATUS")
        .Client()
        .Mqtt()
        .Get("/api/v1/clients/{clientIndex:int}/latency")
        .Description("Current client latency setting")
        .Status("CLIENT_ZONE_STATUS")
        .Client()
        .Mqtt()
        .Get("/api/v1/clients/{clientIndex:int}/zone")
        .Description("Client zone assignment")
        .Status("CLIENT_NAME_STATUS")
        .Client()
        .Mqtt()
        .Get("/api/v1/clients/{clientIndex:int}/name")
        .Description("Client name")
        .RecentlyAdded()
        .Status("CLIENT_CONNECTED")
        .Client()
        .Mqtt()
        .Get("/api/v1/clients/{clientIndex:int}/connected")
        .Description("Client connection status")
        // === MQTT-ONLY STATUS ===
        .Status("CONTROL_STATUS")
        .Zone()
        .Mqtt()
        .Description("Control command execution status (MQTT notifications only)")
        .RecentlyAdded()
        // === COMMAND RESPONSE STATUS ===
        .Status("COMMAND_STATUS")
        .Global()
        .Mqtt()
        .Get("/api/v1/system/commands/status")
        .Description("Command execution status")
        .Status("COMMAND_ERROR")
        .Global()
        .Mqtt()
        .Get("/api/v1/system/commands/errors")
        .Description("Command execution errors")
        .Status("SYSTEM_ERROR")
        .Global()
        .Mqtt()
        .Get("/api/v1/system/errors")
        .Description("System-level errors")
        .Build();
}
