namespace SnapDog2.Tests.Blueprint;

/// <summary>
/// Complete SnapDog2 system specification as fluent blueprint.
/// Single source of truth for all commands, status, protocols, and implementation requirements.
/// </summary>
public static class SnapDogBlueprint
{
    public static readonly Blueprint Spec = Blueprint
        .Define()
        // === ZONE PLAYBACK COMMANDS ===
        .Command("PLAY")
        .Zone()
        .Api()
        .Mqtt()
        .Knx()
        .Post("/zones/{id}/play")
        .Description("Start playback in a zone")
        .Command("PAUSE")
        .Zone()
        .Api()
        .Mqtt()
        .Knx()
        .Post("/zones/{id}/pause")
        .Description("Pause playback in a zone")
        .Command("STOP")
        .Zone()
        .Api()
        .Mqtt()
        .Knx()
        .Post("/zones/{id}/stop")
        .Description("Stop playback in a zone")
        // === VOLUME COMMANDS ===
        .Command("VOLUME")
        .Zone()
        .Api()
        .Mqtt()
        .Put("/zones/{id}/volume")
        .Description("Set zone volume to specific level")
        .Exclude(Protocol.Knx, "Handled by dedicated KNX volume actuators")
        .Command("VOLUME_UP")
        .Zone()
        .Api()
        .Mqtt()
        .Post("/zones/{id}/volume/up")
        .Description("Increase zone volume")
        .Exclude(Protocol.Knx, "Handled by dedicated KNX volume actuators")
        .Command("VOLUME_DOWN")
        .Zone()
        .Api()
        .Mqtt()
        .Post("/zones/{id}/volume/down")
        .Description("Decrease zone volume")
        .Exclude(Protocol.Knx, "Handled by dedicated KNX volume actuators")
        // === MUTE COMMANDS ===
        .Command("MUTE")
        .Zone()
        .Api()
        .Mqtt()
        .Put("/zones/{id}/mute")
        .Description("Set zone mute state")
        .Exclude(Protocol.Knx, "Handled by dedicated KNX mute actuators")
        .Command("MUTE_TOGGLE")
        .Zone()
        .Api()
        .Mqtt()
        .Post("/zones/{id}/mute/toggle")
        .Description("Toggle zone mute state")
        .Exclude(Protocol.Knx, "Toggle commands require state synchronization")
        // === TRACK COMMANDS ===
        .Command("TRACK")
        .Zone()
        .Api()
        .Mqtt()
        .Put("/zones/{id}/track")
        .Description("Set current track by index")
        .Exclude(Protocol.Knx, "Complex track navigation not suitable for building automation")
        .Command("TRACK_NEXT")
        .Zone()
        .Api()
        .Mqtt()
        .Post("/zones/{id}/track/next")
        .Description("Skip to next track")
        .Exclude(Protocol.Knx, "Complex track navigation not suitable for building automation")
        .Command("TRACK_PREVIOUS")
        .Zone()
        .Api()
        .Mqtt()
        .Post("/zones/{id}/track/previous")
        .Description("Skip to previous track")
        .Exclude(Protocol.Knx, "Complex track navigation not suitable for building automation")
        // === PLAYLIST COMMANDS ===
        .Command("PLAYLIST")
        .Zone()
        .Api()
        .Mqtt()
        .Put("/zones/{id}/playlist")
        .Description("Set current playlist")
        .Command("PLAYLIST_NEXT")
        .Zone()
        .Api()
        .Mqtt()
        .Post("/zones/{id}/playlist/next")
        .Description("Switch to next playlist")
        .Exclude(Protocol.Knx, "Complex playlist navigation not suitable for building automation")
        .Command("PLAYLIST_PREVIOUS")
        .Zone()
        .Api()
        .Mqtt()
        .Post("/zones/{id}/playlist/previous")
        .Description("Switch to previous playlist")
        .Exclude(Protocol.Knx, "Complex playlist navigation not suitable for building automation")
        .Command("PLAYLIST_SHUFFLE")
        .Zone()
        .Api()
        .Mqtt()
        .Put("/zones/{id}/playlist/shuffle")
        .Description("Set playlist shuffle mode")
        .Exclude(Protocol.Knx, "Complex state management not suitable for KNX")
        .Command("PLAYLIST_SHUFFLE_TOGGLE")
        .Zone()
        .Api()
        .Mqtt()
        .Post("/zones/{id}/playlist/shuffle/toggle")
        .Description("Toggle playlist shuffle mode")
        .Exclude(Protocol.Knx, "Toggle commands require state synchronization")
        // === CLIENT COMMANDS ===
        .Command("CLIENT_VOLUME")
        .Client()
        .Api()
        .Mqtt()
        .Put("/clients/{id}/volume")
        .Description("Set client volume level")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        .Command("CLIENT_VOLUME_UP")
        .Client()
        .Api()
        .Mqtt()
        .Post("/clients/{id}/volume/up")
        .Description("Increase client volume")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        .Command("CLIENT_VOLUME_DOWN")
        .Client()
        .Api()
        .Mqtt()
        .Post("/clients/{id}/volume/down")
        .Description("Decrease client volume")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        .Command("CLIENT_MUTE")
        .Client()
        .Api()
        .Mqtt()
        .Put("/clients/{id}/mute")
        .Description("Set client mute state")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        .Command("CLIENT_MUTE_TOGGLE")
        .Client()
        .Api()
        .Mqtt()
        .Post("/clients/{id}/mute/toggle")
        .Description("Toggle client mute state")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        .Command("CLIENT_LATENCY")
        .Client()
        .Api()
        .Mqtt()
        .Put("/clients/{id}/latency")
        .Description("Set client audio latency")
        .Exclude(Protocol.Knx, "Network-specific setting not suitable for building automation")
        .Command("CLIENT_NAME")
        .Client()
        .Api()
        .Mqtt()
        .Put("/clients/{id}/name")
        .Description("Set client name")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        .Command("CLIENT_ZONE")
        .Client()
        .Api()
        .Mqtt()
        .Put("/clients/{id}/zone")
        .Description("Assign client to zone")
        .Exclude(Protocol.Knx, "Client-specific network settings not suitable for building automation")
        // === CONTROL COMMANDS ===
        .Command("CONTROL")
        .Zone()
        .Api()
        .Mqtt()
        .Post("/zones/{id}/control")
        .Description("General zone control command")
        // === SYSTEM STATUS ===
        .Status("SYSTEM_STATUS")
        .Global()
        .Api()
        .Mqtt()
        .Get("/system/status")
        .Description("Overall system health and status")
        .Exclude(Protocol.Knx, "Read-only system information not actionable via KNX")
        .Status("VERSION_INFO")
        .Global()
        .Api()
        .Mqtt()
        .Get("/system/version")
        .Description("System version information")
        .Status("SERVER_STATS")
        .Global()
        .Api()
        .Mqtt()
        .Get("/system/stats")
        .Description("Server performance statistics")
        .Status("ZONES_INFO")
        .Global()
        .Api()
        .Mqtt()
        .Get("/zones")
        .Description("Information about all zones")
        .Status("CLIENTS_INFO")
        .Global()
        .Api()
        .Mqtt()
        .Get("/clients")
        .Description("Information about all clients")
        .Exclude(Protocol.Knx, "Read-only system information not actionable via KNX")
        // === ZONE STATUS ===
        .Status("ZONE_STATE")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}")
        .Description("Complete zone state information")
        .Status("VOLUME_STATUS")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/volume")
        .Description("Current zone volume level")
        .Status("MUTE_STATUS")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/mute")
        .Description("Current zone mute state")
        .Status("PLAYBACK_STATE")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/playback")
        .Description("Current playback state")
        // === TRACK STATUS ===
        .Status("TRACK_STATUS")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/track")
        .Description("Current track information")
        .Status("TRACK_METADATA")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/track/metadata")
        .Description("Track metadata (title, artist, album, etc.)")
        .Exclude(Protocol.Knx, "Read-only metadata not actionable via KNX")
        .Status("TRACK_POSITION_STATUS")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/track/position")
        .Description("Current track position")
        .Status("TRACK_PROGRESS_STATUS")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/track/progress")
        .Description("Track progress percentage")
        .Status("TRACK_REPEAT_STATUS")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/track/repeat")
        .Description("Track repeat mode status")
        // === PLAYLIST STATUS ===
        .Status("PLAYLIST_STATUS")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/playlist")
        .Description("Current playlist information")
        .Status("PLAYLIST_INFO")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/playlist/info")
        .Description("Detailed playlist information")
        .Status("PLAYLIST_NAME_STATUS")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/playlist/name")
        .Description("Current playlist name")
        .RecentlyAdded()
        .Status("PLAYLIST_COUNT_STATUS")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/playlist/count")
        .Description("Number of tracks in current playlist")
        .RecentlyAdded()
        .Status("PLAYLIST_SHUFFLE_STATUS")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/playlist/shuffle")
        .Description("Playlist shuffle mode status")
        .Status("PLAYLIST_REPEAT_STATUS")
        .Zone()
        .Api()
        .Mqtt()
        .Get("/zones/{id}/playlist/repeat")
        .Description("Playlist repeat mode status")
        // === CLIENT STATUS ===
        .Status("CLIENT_STATE")
        .Client()
        .Api()
        .Mqtt()
        .Get("/clients/{id}")
        .Description("Complete client state information")
        .Status("CLIENT_VOLUME_STATUS")
        .Client()
        .Api()
        .Mqtt()
        .Get("/clients/{id}/volume")
        .Description("Current client volume level")
        .Status("CLIENT_MUTE_STATUS")
        .Client()
        .Api()
        .Mqtt()
        .Get("/clients/{id}/mute")
        .Description("Current client mute state")
        .Status("CLIENT_LATENCY_STATUS")
        .Client()
        .Api()
        .Mqtt()
        .Get("/clients/{id}/latency")
        .Description("Current client latency setting")
        .Status("CLIENT_ZONE_STATUS")
        .Client()
        .Api()
        .Mqtt()
        .Get("/clients/{id}/zone")
        .Description("Client zone assignment")
        .Status("CLIENT_NAME_STATUS")
        .Client()
        .Api()
        .Mqtt()
        .Get("/clients/{id}/name")
        .Description("Client name")
        .RecentlyAdded()
        .Status("CLIENT_CONNECTED")
        .Client()
        .Api()
        .Mqtt()
        .Get("/clients/{id}/connected")
        .Description("Client connection status")
        // === MQTT-ONLY STATUS ===
        .Status("CONTROL_STATUS")
        .Zone()
        .Mqtt()
        .Description("Control command execution status (MQTT notifications only)")
        .RecentlyAdded()
        // === COMMAND RESPONSE STATUS ===
        .Status("COMMAND_STATUS")
        .Global()
        .Api()
        .Mqtt()
        .Get("/system/commands/status")
        .Description("Command execution status")
        .Status("COMMAND_ERROR")
        .Global()
        .Api()
        .Mqtt()
        .Get("/system/commands/errors")
        .Description("Command execution errors")
        .Status("SYSTEM_ERROR")
        .Global()
        .Api()
        .Mqtt()
        .Get("/system/errors")
        .Description("System-level errors")
        .Build();
}
