receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s
  
  resourcedetection:
    detectors: [env, system]
    timeout: 2s
  
  resource:
    attributes:
      - key: service.namespace
        value: snapdog
        action: upsert
      - key: deployment.environment
        value: development
        action: upsert

  signozspanmetrics/delta:
    metrics_exporter: signozclickhousemetrics
    metrics_flush_interval: 60s
    latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 50ms, 100ms, 250ms, 500ms, 1000ms, 1400ms, 2000ms, 5s, 10s, 20s, 40s, 60s]
    dimensions_cache_size: 100000
    aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
    enable_exp_histogram: true
    dimensions:
      - name: service.namespace
        default: snapdog
      - name: deployment.environment
        default: development
      - name: service.version
      - name: host.name
      - name: container.name

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

exporters:
  clickhousetraces:
    datasource: tcp://signoz-clickhouse:9000/signoz_traces
    low_cardinal_exception_grouping: false
    use_new_schema: true
  
  signozclickhousemetrics:
    dsn: tcp://signoz-clickhouse:9000/signoz_metrics
  
  clickhouselogsexporter:
    dsn: tcp://signoz-clickhouse:9000/signoz_logs
    timeout: 10s
    use_new_schema: true

service:
  telemetry:
    logs:
      level: info
      encoding: json
    metrics:
      address: 0.0.0.0:8888
  
  extensions:
    - health_check
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [signozspanmetrics/delta, batch, resource, resourcedetection]
      exporters: [clickhousetraces]
    
    metrics:
      receivers: [otlp]
      processors: [batch, resource, resourcedetection]
      exporters: [signozclickhousemetrics]
    
    logs:
      receivers: [otlp]
      processors: [batch, resource, resourcedetection]
      exporters: [clickhouselogsexporter]
