global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'signoz'
    static_configs:
      - targets: ['localhost:8080']
    scrape_interval: 60s
    metrics_path: '/metrics'

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['signoz-otel-collector:8888']
    scrape_interval: 60s
    metrics_path: '/metrics'
