version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI port
      - "14268:14268" # HTTP collector
      - "6831:6831/udp" # Agent - Thrift over UDP
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - snapdog-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - snapdog-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/snapdog_overview.json
    networks:
      - snapdog-net
    depends_on:
      - prometheus

networks:
  snapdog-net:
    driver: bridge