receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  resource:
    attributes:
      - key: service.namespace
        value: snapdog
        action: upsert
      - key: deployment.environment
        value: development
        action: upsert

exporters:
  # Prometheus metrics exporter for Grafana
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      environment: development
      service: snapdog

  # Debug exporter for development
  debug:
    verbosity: normal
    sampling_initial: 5
    sampling_thereafter: 200

  # Additional debug exporter for traces and logs
  debug/verbose:
    verbosity: detailed
    sampling_initial: 10
    sampling_thereafter: 100

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, debug/verbose]
    
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [prometheus, debug]
    
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, debug/verbose]

  extensions: []
  
  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888
